---
title: "Visualising spatial patterns"
author: "ajsmit"
date: "2023-03-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}
library(tidyverse)
library(data.table)
library(ggthemes)
library(sf)
library(rnaturalearth)
library(rnaturalearthhires)
library(terra)
library(tidyterra)
library(doMC); doMC::registerDoMC(cores = 8)
```

```{r}
NE_proj <- "+proj=natearth +lon_0=10 "
WGS84_proj <- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"

world <- ne_countries(returnclass = 'sf',
  scale = 10, type = "countries") |> 
  select(continent, sovereignt, iso_a3) |> 
  st_break_antimeridian(lon_0 = 10) |>
  st_transform(NE_proj) |> 
  group_by(continent) |>
  summarise()

load("data/bbox.Rdata")
margin <- 20
xmin <- min(bbox[, "lonmin"]) - margin; xmax <- max(bbox[, "lonmax"]) + margin
ymin <- min(bbox[, "latmin"]) - 5; ymax <- max(bbox[, "latmax"]) + margin
bbox_sf <- st_sfc(st_point(c(xmin, ymin)), st_point(c(xmax, ymax)),
                         crs = WGS84_proj)
bbox_trans <- st_transform(bbox_sf, NE_proj)

roi_cropped <- world |> 
  st_crop(bbox_trans)
```

```{r}
csv_dir <- "/Volumes/OceanData/AVHRR_OI-NCEI-L4-GLOB-v2.0/EXEBUS_MHW"
files  <- as.list(list.files(csv_dir, recursive = TRUE, pattern = '.csv',
                             full.names = TRUE))

sst_list <- lapply(files, function(i) {
  fread(i) |> 
    group_by(lon, lat) |> 
    summarise(temp_mean = mean(temp, na.rm = TRUE), .groups = "drop") |> 
  as_spatraster(xycols = c(1,2), crs = WGS84_proj) |> 
  terra::project(NE_proj)
})
```

```{r}
ggplot() +
  geom_spatraster(data = sst_list[[1]], aes(fill = temp_mean)) +
  geom_spatraster(data = sst_list[[2]], aes(fill = temp_mean)) +
  geom_spatraster(data = sst_list[[3]], aes(fill = temp_mean)) +
  geom_spatraster(data = sst_list[[4]], aes(fill = temp_mean)) +
  geom_spatraster(data = sst_list[[5]], aes(fill = temp_mean)) +
  geom_sf(data = roi_cropped, colour = "black", fill = "grey70") +
   scale_fill_continuous(type = "viridis") +
  guides(size = "none",
    colour = guide_colourbar("SST")) +
  coord_sf(expand = FALSE) +
  labs(x = NULL, y = NULL,
    title = "EXEBUS MHW focal regions",
    subtitle = "Composite SST") +
  theme_minimal() 
```
