---
title: "The Analysis Starts Here"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

Welcome to my website where I develop the research workflows for the EXEBUS Marine Heatwave (MHW), Marine Cold Spell (MCS), and Extreme Thermal Fluctuations (ETF) analysis.

# Sourcing and downloading data

Here I will define the study domains and describe the steps taken to acquire the data used in the ensuing analyses. Case Study 3 has several areas if interest corresponding to the following paper titles, so I download one large area to enclose them all using the python script.

The bounding box is 12.5째E to 20째E and -42.5째S to -25째S.

```{r}
lonmin <- 12.5
lonmax <- 20
latmin <- 42.5
latmax <- -25
```

See /Volumes/OceanData/AVHRR_OI-NCEI-L4-GLOB-v2.0/EXEBUS_MHW

> ./subset_dataset.py -s 19810901 -f 20200405 -b 12.5 20 -42.5 -25 -x AVHRR_OI-NCEI-L4-GLOB-v2.0
> ./subset_dataset.py -s 20200406 -f 20230314 -b 12.5 20 -42.5 -25 -x AVHRR_OI-NCEI-L4-GLOB-v2.1

## Extreme events in the coastal jet current over the Agulhas Bank and West Coast

* west coast (St Helena Bay)
* Orange River bank
* the Agulhas retroflection

## Comparison of marine heatwaves between four tropical upwelling systems

# Another heading


